# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Test with pytest
      run: |
        python runner.py --set smoke_test
        
    - name: HTML Preview
      id: html_preview_ios
      uses: pavi2410/html-preview-action@v2
      with:
        html_file: 'report.html' 

    - name: Print HTML Link
      run: |
        echo '${{ steps.html_preview_ios.outputs.url }}'
        
    - name: Publish Test Results - iOS
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        junit_files: "results/latest/*.xml"
