# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run REST framework tests
      run: |
        python runner.py --set smoke_test

    - uses: actions/upload-artifact@v3
      with:
        name: test-run-results-artifacts
        path: results/latest
      
    - name: Publish HTML report
      if: always() # We want this to always run, even if test fail prior to this step running
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.ASSI_TOKEN_GITHUB }}
        publish_branch: gh-pages
        publish_dir: results/latest # This is where index.html will be output
        #force_orphan: true
        keep_files: true # Set this to true to make sure we don't wipe out the other content in GitHub Pages
        user_name: 'github-actions[bot]' # This will be the username that gets stamped in the repo commit
        user_email: 'github-actions[bot]@users.noreply.github.com' # This will be the user email that gets stamped in the repo commit
        
    - name: HTML Report Link
      run: |
        echo 'https://assinet.github.io/rest-api-tests-action'

    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: "results/latest/*.xml"
      if: always()

